export class Country {

  constructor() {
    'ngInject';
  }

  get() {
    return [{
      key: 'afganistan',
      value: 'Afganistán'
    }, {
      key: 'albania',
      value: 'Albania'
    }, {
      key: 'alemania',
      value: 'Alemania'
    }, {
      key: 'andorra',
      value: 'Andorra'
    }, {
      key: 'angola',
      value: 'Angola'
    }, {
      key: 'antigua-y-barbuda',
      value: 'Antigua y Barbuda'
    }, {
      key: 'arabia-saudita',
      value: 'Arabia Saudita'
    }, {
      key: 'argelia',
      value: 'Argelia'
    }, {
      key: 'argentina',
      value: 'Argentina'
    }, {
      key: 'armenia',
      value: 'Armenia'
    }, {
      key: 'australia',
      value: 'Australia'
    }, {
      key: 'austria',
      value: 'Austria'
    }, {
      key: 'azerbaiyan',
      value: 'Azerbaiyán'
    }, {
      key: 'bahamas',
      value: 'Bahamas'
    }, {
      key: 'banglades',
      value: 'Bangladés'
    }, {
      key: 'barbados',
      value: 'Barbados'
    }, {
      key: 'barein',
      value: 'Baréin'
    }, {
      key: 'belgica',
      value: 'Bélgica'
    }, {
      key: 'belice',
      value: 'Belice'
    }, {
      key: 'benin',
      value: 'Benín'
    }, {
      key: 'bielorrusia',
      value: 'Bielorrusia'
    }, {
      key: 'birmania',
      value: 'Birmania'
    }, {
      key: 'bolivia',
      value: 'Bolivia'
    }, {
      key: 'bosnia-herzegovina',
      value: 'Bosnia-Herzegovina'
    }, {
      key: 'botsuana',
      value: 'Botsuana'
    }, {
      key: 'brasil',
      value: 'Brasil'
    }, {
      key: 'brunei',
      value: 'Brunéi'
    }, {
      key: 'bulgaria',
      value: 'Bulgaria'
    }, {
      key: 'burkina-faso',
      value: 'Burkina Faso'
    }, {
      key: 'burundi',
      value: 'Burundi'
    }, {
      key: 'butan',
      value: 'Bután'
    }, {
      key: 'cabo-verde',
      value: 'Cabo Verde'
    }, {
      key: 'camboya',
      value: 'Camboya'
    }, {
      key: 'camerun',
      value: 'Camerún'
    }, {
      key: 'canada',
      value: 'Canadá'
    }, {
      key: 'catar',
      value: 'Catar'
    }, {
      key: 'chad',
      value: 'Chad'
    }, {
      key: 'chile',
      value: 'Chile'
    }, {
      key: 'china',
      value: 'China'
    }, {
      key: 'chipre',
      value: 'Chipre'
    }, {
      key: 'colombia',
      value: 'Colombia'
    }, {
      key: 'comoras',
      value: 'Comoras'
    }, {
      key: 'congo',
      value: 'Congo'
    }, {
      key: 'corea-del-norte',
      value: 'Corea del Norte'
    }, {
      key: 'corea-del-sur',
      value: 'Corea del Sur'
    }, {
      key: 'costa-de-marfil',
      value: 'Costa de Marfil'
    }, {
      key: 'costa-rica',
      value: 'Costa Rica'
    }, {
      key: 'croacia',
      value: 'Croacia'
    }, {
      key: 'cuba',
      value: 'Cuba'
    }, {
      key: 'dinamarca',
      value: 'Dinamarca'
    }, {
      key: 'dominica',
      value: 'Dominica'
    }, {
      key: 'ecuador',
      value: 'Ecuador'
    }, {
      key: 'egipto',
      value: 'Egipto'
    }, {
      key: 'el-salvador',
      value: 'El Salvador'
    }, {
      key: 'emiratos-arabes-unidos',
      value: 'Emiratos Árabes Unidos'
    }, {
      key: 'eritrea',
      value: 'Eritrea'
    }, {
      key: 'eslovaquia',
      value: 'Eslovaquia'
    }, {
      key: 'eslovenia',
      value: 'Eslovenia'
    }, {
      key: 'espania',
      value: 'España'
    }, {
      key: 'estados-unidos',
      value: 'Estados Unidos'
    }, {
      key: 'estonia',
      value: 'Estonia'
    }, {
      key: 'etiopia',
      value: 'Etiopía'
    }, {
      key: 'filipinas',
      value: 'Filipinas'
    }, {
      key: 'finlandia',
      value: 'Finlandia'
    }, {
      key: 'fiyi',
      value: 'Fiyi'
    }, {
      key: 'francia',
      value: 'Francia'
    }, {
      key: 'gabon',
      value: 'Gabón'
    }, {
      key: 'gambia',
      value: 'Gambia'
    }, {
      key: 'georgia',
      value: 'Georgia'
    }, {
      key: 'ghana',
      value: 'Ghana'
    }, {
      key: 'granada',
      value: 'Granada'
    }, {
      key: 'grecia',
      value: 'Grecia'
    }, {
      key: 'guatemala',
      value: 'Guatemala'
    }, {
      key: 'guinea',
      value: 'Guinea'
    }, {
      key: 'guinea-ecuatorial',
      value: 'Guinea Ecuatorial'
    }, {
      key: 'guinea-bisau',
      value: 'Guinea-Bisáu'
    }, {
      key: 'guyana',
      value: 'Guyana'
    }, {
      key: 'haiti',
      value: 'Haití'
    }, {
      key: 'honduras',
      value: 'Honduras'
    }, {
      key: 'hungria',
      value: 'Hungría'
    }, {
      key: 'india',
      value: 'India'
    }, {
      key: 'indonesia',
      value: 'Indonesia'
    }, {
      key: 'irak',
      value: 'Irak'
    }, {
      key: 'iran',
      value: 'Irán'
    }, {
      key: 'irlanda',
      value: 'Irlanda'
    }, {
      key: 'islandia',
      value: 'Islandia'
    }, {
      key: 'islas-marshall',
      value: 'Islas Marshall'
    }, {
      key: 'islas-salomon',
      value: 'Islas Salomón'
    }, {
      key: 'israel',
      value: 'Israel'
    }, {
      key: 'italia',
      value: 'Italia'
    }, {
      key: 'jamaica',
      value: 'Jamaica'
    }, {
      key: 'japon',
      value: 'Japón'
    }, {
      key: 'jordania',
      value: 'Jordania'
    }, {
      key: 'kazajistan',
      value: 'Kazajistán'
    }, {
      key: 'kenia',
      value: 'Kenia'
    }, {
      key: 'kirguistan',
      value: 'Kirguistán'
    }, {
      key: 'kiribati',
      value: 'Kiribati'
    }, {
      key: 'kosovo',
      value: 'Kosovo'
    }, {
      key: 'kuwait',
      value: 'Kuwait'
    }, {
      key: 'laos',
      value: 'Laos  '
    }, {
      key: 'lesoto',
      value: 'Lesoto'
    }, {
      key: 'letonia',
      value: 'Letonia'
    }, {
      key: 'libano',
      value: 'Líbano'
    }, {
      key: 'liberia',
      value: 'Liberia'
    }, {
      key: 'libia',
      value: 'Libia'
    }, {
      key: 'liechtenstein',
      value: 'Liechtenstein'
    }, {
      key: 'lituania',
      value: 'Lituania'
    }, {
      key: 'luxemburgo',
      value: 'Luxemburgo'
    }, {
      key: 'macedonia',
      value: 'Macedonia'
    }, {
      key: 'madagascar',
      value: 'Madagascar'
    }, {
      key: 'malasia',
      value: 'Malasia'
    }, {
      key: 'malaui',
      value: 'Malaui'
    }, {
      key: 'maldivas',
      value: 'Maldivas'
    }, {
      key: 'mali',
      value: 'Malí'
    }, {
      key: 'malta',
      value: 'Malta'
    }, {
      key: 'marruecos',
      value: 'Marruecos'
    }, {
      key: 'mauricio',
      value: 'Mauricio'
    }, {
      key: 'mauritania',
      value: 'Mauritania'
    }, {
      key: 'mexico',
      value: 'México'
    }, {
      key: 'micronesia',
      value: 'Micronesia'
    }, {
      key: 'moldavia',
      value: 'Moldavia'
    }, {
      key: 'monaco',
      value: 'Mónaco'
    }, {
      key: 'mongolia',
      value: 'Mongolia'
    }, {
      key: 'montenegro',
      value: 'Montenegro'
    }, {
      key: 'mozambique',
      value: 'Mozambique'
    }, {
      key: 'namibia',
      value: 'Namibia'
    }, {
      key: 'nauru',
      value: 'Nauru'
    }, {
      key: 'nepal',
      value: 'Nepal'
    }, {
      key: 'nicaragua',
      value: 'Nicaragua'
    }, {
      key: 'niger',
      value: 'Níger'
    }, {
      key: 'nigeria',
      value: 'Nigeria'
    }, {
      key: 'noruega',
      value: 'Noruega'
    }, {
      key: 'nueva-zelanda',
      value: 'Nueva Zelanda'
    }, {
      key: 'oman',
      value: 'Omán'
    }, {
      key: 'paises-bajos',
      value: 'Países Bajos'
    }, {
      key: 'pakistan',
      value: 'Pakistán'
    }, {
      key: 'palaos',
      value: 'Palaos'
    }, {
      key: 'palestina',
      value: 'Palestina'
    }, {
      key: 'panama',
      value: 'Panamá'
    }, {
      key: 'papua-nueva-guinea',
      value: 'Papúa Nueva Guinea'
    }, {
      key: 'paraguay',
      value: 'Paraguay'
    }, {
      key: 'peru',
      value: 'Perú'
    }, {
      key: 'polonia',
      value: 'Polonia'
    }, {
      key: 'portugal',
      value: 'Portugal'
    }, {
      key: 'reino-unido',
      value: 'Reino Unido'
    }, {
      key: 'republica-centroafricana',
      value: 'República Centroafricana'
    }, {
      key: 'republica-checa',
      value: 'República Checa'
    }, {
      key: 'republica-democratica-del-congo',
      value: 'República Democrática del Congo'
    }, {
      key: 'republica-dominicana',
      value: 'República Dominicana'
    }, {
      key: 'ruanda',
      value: 'Ruanda'
    }, {
      key: 'rumania',
      value: 'Rumania'
    }, {
      key: 'rusia',
      value: 'Rusia'
    }, {
      key: 'samoa',
      value: 'Samoa'
    }, {
      key: 'san-cristobal-y-nieves',
      value: 'San Cristóbal y Nieves'
    }, {
      key: 'san-marino',
      value: 'San Marino'
    }, {
      key: 'san-vicente-y-las-granadinas',
      value: 'San Vicente y las Granadinas'
    }, {
      key: 'santa-lucia',
      value: 'Santa Lucía'
    }, {
      key: 'santo-tome-y-principe',
      value: 'Santo Tomé y Príncipe'
    }, {
      key: 'senegal',
      value: 'Senegal'
    }, {
      key: 'serbia',
      value: 'Serbia'
    }, {
      key: 'seychelles',
      value: 'Seychelles'
    }, {
      key: 'sierra-leona',
      value: 'Sierra Leona'
    }, {
      key: 'singapur',
      value: 'Singapur'
    }, {
      key: 'siria',
      value: 'Siria'
    }, {
      key: 'somalia',
      value: 'Somalia'
    }, {
      key: 'sri-lanka',
      value: 'Sri Lanka'
    }, {
      key: 'suazilandia',
      value: 'Suazilandia'
    }, {
      key: 'sudafrica',
      value: 'Sudáfrica'
    }, {
      key: 'sudan',
      value: 'Sudán'
    }, {
      key: 'sudan-del-sur',
      value: 'Sudán del Sur'
    }, {
      key: 'suecia',
      value: 'Suecia'
    }, {
      key: 'suiza',
      value: 'Suiza'
    }, {
      key: 'surinam',
      value: 'Surinam'
    }, {
      key: 'tailandia',
      value: 'Tailandia'
    }, {
      key: 'taiwan',
      value: 'Taiwán'
    }, {
      key: 'tanzania',
      value: 'Tanzania'
    }, {
      key: 'tayikistan',
      value: 'Tayikistán'
    }, {
      key: 'timor-oriental',
      value: 'Timor Oriental'
    }, {
      key: 'togo',
      value: 'Togo'
    }, {
      key: 'tonga',
      value: 'Tonga'
    }, {
      key: 'trinidad-y-tobago',
      value: 'Trinidad y Tobago'
    }, {
      key: 'tunez',
      value: 'Túnez'
    }, {
      key: 'turkmenistan',
      value: 'Turkmenistán'
    }, {
      key: 'turquia',
      value: 'Turquía'
    }, {
      key: 'tuvalu',
      value: 'Tuvalu'
    }, {
      key: 'ucrania',
      value: 'Ucrania'
    }, {
      key: 'uganda',
      value: 'Uganda'
    }, {
      key: 'uruguay',
      value: 'Uruguay'
    }, {
      key: 'uzbekistan',
      value: 'Uzbekistán'
    }, {
      key: 'vanuatu',
      value: 'Vanuatu'
    }, {
      key: 'vaticano',
      value: 'Vaticano'
    }, {
      key: 'venezuela',
      value: 'Venezuela'
    }, {
      key: 'vietnam',
      value: 'Vietnam'
    }, {
      key: 'yemen',
      value: 'Yemen'
    }, {
      key: 'yibuti',
      value: 'Yibuti'
    }, {
      key: 'zambia',
      value: 'Zambia'
    }, {
      key: 'zimbabue',
      value: 'Zimbabue'
    }];
  }
}
